name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, llvm-tools-preview
      - name: Install bootimage
        run: cargo install bootimage --target x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
